### ISSUE TITLE
Not respecting language paths

### ISSUE THREAD

**Issue by trashhalo** [codeclimate/codeclimate-duplication#126]
according to issue #73 you can add a path to a language config to force it to read certain files. Is that still the case?

```
 duplication:
    enabled: true
    config:
      languages:
        javascript:
          paths:
            - "app/components/**/*.ts"
```
As far as I can tell its not loading the ts files. [You can see the cc.com branch build here](https://codeclimate.com/repos/533057d6e30ba05fe3000862/compare/lets-make-codeclimate-angry#issues)
