### ISSUE TITLE
Allow setting separate language specific mass thresholds for identical and similar code

### ISSUE THREAD

**Issue by rdimartino** [codeclimate/codeclimate-duplication#326]
I can set separate check mass thresholds with
```YAML
checks:
  identical-code:
    config:
      threshold: 25
  similar-code:
    config:
      threshold: 50
```
but those aren't language specific.

I can set a language-specific mass threshold with
```YAML
plugins:
  duplication:
    config:
      languages:
        javascript:
          mass_threshold: 50
```
but that sets the threshold for both identical and similar code.

I want to be able to do something like
```YAML
plugins:
  duplication:
    config:
      languages:
        javascript:
          identical-code:
            mass_threshold: 25
          similar-code:
            mass_threshold: 50
```

**Comment by kevinleturc** [comment]
👍

**Comment by efueger** [comment]
Hi @kevinleturc and @rdimartino - thanks for the suggestion. Although I don't have an ETA, this is something that we're looking at adding.

Can you tell me a little bit more about your use case?
- what languages are you using
- if you're getting false positives for a specific language, are you using any frameworks or other standard conventions that have boilerplate similar/identical code?

**Comment by rdimartino** [comment]
@efueger We're using a Rails backend with a React frontend. We were getting some false positives when using some of our more template-like React components that have a little bit more boilerplate but can't really be abstracted further.

As a work around for this we currently doing something like:
```
checks:
  identical-code:
    config:
      threshold: 35
...
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 75
```

but this is obviously not ideal.
