### ISSUE TITLE
disable, enable, ignore-next pragmas

### ISSUE THREAD

**Issue by bennypowers** [codeclimate/codeclimate-duplication#355]
JS/TS developers are used to:
```js
/* eslint-disable */
/* eslint-enable */
/* istanbul ignore next */
/* istanbul ignore else */
```

It would be nice to have 
```js
/* codeclimate-duplication-disable */
/* codeclimate-duplication-enable */
```

Use cases: 
- config blocks, e.g. routing tables, `yargs` configuration blocks
- test files
- complex class inheritance statements that only slightly modify the base class

**Comment by efueger** [comment]
Hi @bennypowers - thanks for the suggestion! And great idea. I'll pass this along to our product team.

Best,
Emily

**Comment by filipesperandio** [comment]
Good idea, till then, it is worth remembering we can also exclude paths for specific plugins:

```yml
plugins:
  duplication:
    enabled: true
    exclude_paths:
      - config.js
      - routes/
```
