### ISSUE TITLE
Configuration clearity

### ISSUE THREAD

**Issue by SilentImp** [codeclimate/codeclimate-duplication#359]
Hi, maybe it would be nice to provide more documentation examples and information about default values.
For example I created this config:
```
  duplication:
    enabled: true
    config:
      languages:
        - javascript
      checks:
        mass_threshold: 50
        similar-code:
          config:
            threshold: 60
        identical-code:
          config:
            threshold: 40
```
