### ISSUE TITLE
some excluded fingerprints are being ignored

### ISSUE THREAD

**Issue by jamesla** [codeclimate/codeclimate-duplication#371]
I have a code base that has a huge number of violations - and there isn't an appetite to resolve them upfront so I am wanting to add all of the current violations as fingerprint exclusions and then resolve any violations going forward.

in my .codeclimate.yml file I have the following config:

```
plugins:
  eslint:
    enabled: true
    channel: "eslint-7"
    exclude_fingerprints:
      - 76a4e9532a0359de7e912861355e8ba7
      - a261e88ffbb7f840e60baf9ad3b32ff9
      - ....
```

Now when I run `codeclimate analyze` some of the fingerprints are being excluded but majority of them are being ignored and still appear as errors in the output. 

I've done a bit of testing and some of the violations work and some don't - they all appear in the json output with valid fingerprints though.

I've also tried this in a couple of different projects to rule out my project playing up but it appears to have the same behaviour.

Has anybody experienced this before and is there a way to ensure that all of the excluded fingerprints are ignored?
