### ISSUE TITLE
Error when using customized mass_threshold with python language

### ISSUE THREAD

**Issue by benjixx** [codeclimate/codeclimate-duplication#48]
I am currently in the process of switching from the traditional code climate to the Code Climate Platform. To test things, I run this on Mac OS 10.11.1, have ```docker-machine``` configured appropriately, installed ```codeclimate``` via ```brew```.

But I have problems running duplication check with the following config (customizing ```mass_threshold```):

```yml
# .codeclimate.yml
---
engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 40
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
    - "**.py"
exclude_paths:
  - "docs/source/conf.py"
  - "tests/**/*"
```

Running ```codeclimate analyze``` fails with the following error:
```
Starting analysis
Running duplication: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine duplication failed with status 1 and stderr
/usr/lib/ruby/gems/2.2.0/gems/flay-2.6.1/lib/flay.rb:324:in `<': comparison of Fixnum with String failed (ArgumentError)
	from /usr/lib/ruby/gems/2.2.0/gems/flay-2.6.1/lib/flay.rb:324:in `block in process_sexp'
	from /usr/lib/ruby/gems/2.2.0/gems/sexp_processor-4.6.0/lib/sexp.rb:92:in `[]'
	from /usr/lib/ruby/gems/2.2.0/gems/sexp_processor-4.6.0/lib/sexp.rb:92:in `block in deep_each'
	from /usr/lib/ruby/gems/2.2.0/gems/sexp_processor-4.6.0/lib/sexp.rb:117:in `block in each_sexp'
	from /usr/lib/ruby/gems/2.2.0/gems/sexp_processor-4.6.0/lib/sexp.rb:114:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/sexp_processor-4.6.0/lib/sexp.rb:114:in `each_sexp'
	from /usr/lib/ruby/gems/2.2.0/gems/sexp_processor-4.6.0/lib/sexp.rb:91:in `deep_each'
	from /usr/lib/ruby/gems/2.2.0/gems/flay-2.6.1/lib/flay.rb:322:in `process_sexp'
	from /usr/src/app/lib/cc/engine/analyzers/reporter.rb:32:in `process_sexp'
	from /usr/src/app/lib/cc/engine/analyzers/reporter.rb:18:in `block in run'
	from /usr/src/app/lib/cc/engine/analyzers/reporter.rb:17:in `each'
	from /usr/src/app/lib/cc/engine/analyzers/reporter.rb:17:in `run'
	from /usr/src/app/lib/cc/engine/duplication.rb:32:in `block in run'
	from /usr/src/app/lib/cc/engine/duplication.rb:29:in `each'
	from /usr/src/app/lib/cc/engine/duplication.rb:29:in `run'
	from /usr/src/app/bin/duplication:16:in `<main>'
```

The problem seems to be related to the ```mass_threshold``` setting (or probably to the use of hash), because everything runs fine and also outputs duplication problems as expected when running with the following config:

```yml
# .codeclimate.yml
---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - python
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
    - "**.py"
exclude_paths:
  - "docs/source/conf.py"
  - "tests/**/*"
```

The error above occurs with the official ```codeclimate/codeclimate-duplication``` image provided on Docker Hub, which seems to be some weeks old already.
