### ISSUE TITLE
Adding extension to JS Analyzer

### ISSUE THREAD

**Issue by 8bitDesigner** [codeclimate/codeclimate-duplication#73]
Hi all, we use [sprockets-es6] in our Rails project which requires all ES6-ish JS files be written with the `.es6` extension. As best I can tell, this analyzer only uses `.js` and `.jsx` extensions when building its list of files to analyze. Is there any way to add `.es6` to that list?

**Comment by GordonDiggs** [comment]
@8bitDesigner yep! If you specify a `paths` key in your `.codeclimate.yml` file, you should be able to include them. For example:

```yaml
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          paths:
            - "**/*.es6"
  ...
```
